### ISSUE TITLE
Uncaught ReferenceError: DIV#board not found after 3 attempts

### ISSUE THREAD

**Issue by kitofr** [NordMagnus/Trello-Folds#63]
Google Chrome is up to date
Version 78.0.3904.108 (Official Build) (64-bit)

Console reads:
```
Running TRELLO FOLDS Chrome extension
content.js:4 Extension version: 0.9.6
content.js:5 jQuery version: 3.4.1
INITIALIZING NEW BOARD: XXXXXXX (old board ID: undefined)
tdom.js:221 Trying to find DIV#board again (attempt 2)
tdom.js:221 Trying to find DIV#board again (attempt 3)
Uncaught ReferenceError: DIV#board not found after 3 attempts
    at Object.watchForMutations (tdom.js:226)
    at tdom.js:222
  | watchForMutations | @ | tdom.js:226
-- | -- | -- | --
  | (anonymous) | @ | tdom.js:222
  | setTimeout (async) |   |  
  | watchForMutations | @ | tdom.js:220
  | (anonymous) | @ | tdom.js:222
```

**Comment by NordMagnus** [comment]
Does this happen consistently. Anything you can think of context wise, e.g. a slow connection? Usually this happens if the board does not load within a certain time.

It's difficult to find a fool proof method to fix this. One easy-to-implement solution could be being able to configure the timeout and/or retry attempts.

**Comment by kitofr** [comment]
It did happen consistently. There's not really "slow" connection as _a lot of boards and cards_.

**Comment by NordMagnus** [comment]
I'm closing this now since I didn't have time to look into it sooner. If it is still an issue please create new issue or comment on this.
